#!/usr/bin/env bash
# UpInbox self-host setup script
# Usage: curl -fsSL https://upinbox.ai/install.sh | bash
# Or:    bash scripts/setup.sh [--domain example.com] [--email admin@example.com]

set -euo pipefail

# ─── Colors ───────────────────────────────────────────────────────────────────

RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
BOLD='\033[1m'
NC='\033[0m' # No Color

info()  { echo -e "${BLUE}ℹ${NC}  $*"; }
ok()    { echo -e "${GREEN}✓${NC}  $*"; }
warn()  { echo -e "${YELLOW}⚠${NC}  $*"; }
error() { echo -e "${RED}✗${NC}  $*" >&2; }
die()   { error "$*"; exit 1; }
step()  { echo -e "\n${BOLD}── $* ──${NC}"; }

# ─── Defaults ─────────────────────────────────────────────────────────────────

DOMAIN=""
ADMIN_EMAIL=""
INSTALL_DIR="${INSTALL_DIR:-/opt/upinbox}"
COMPOSE_VERSION="v2.28.1"

# ─── Parse args ───────────────────────────────────────────────────────────────

while [[ $# -gt 0 ]]; do
  case "$1" in
    --domain)    DOMAIN="$2"; shift 2 ;;
    --email)     ADMIN_EMAIL="$2"; shift 2 ;;
    --dir)       INSTALL_DIR="$2"; shift 2 ;;
    --help|-h)
      echo "Usage: $0 [--domain example.com] [--email admin@example.com] [--dir /opt/upinbox]"
      exit 0 ;;
    *) die "Unknown argument: $1" ;;
  esac
done

# ─── Banner ───────────────────────────────────────────────────────────────────

cat <<'EOF'
  _   _       ___       _
 | | | |_ __ |_ _|_ __ | |__   _____  __
 | | | | '_ \ | || '_ \| '_ \ / _ \ \/ /
 | |_| | |_) || || | | | |_) | (_) >  <
  \___/| .__/___|_| |_|_.__/ \___/_/\_\
       |_|

  Self-Host Setup  •  Community tier is free forever
  Docs: https://upinbox.ai/docs/SELF-HOSTING.md
EOF

echo

# ─── Check prerequisites ──────────────────────────────────────────────────────

step "Checking prerequisites"

check_cmd() {
  if command -v "$1" &>/dev/null; then
    ok "$1 found ($(command -v "$1"))"
  else
    die "$1 not found. Please install it first."
  fi
}

check_cmd docker
check_cmd openssl

# Docker Compose v2 check
if docker compose version &>/dev/null 2>&1; then
  ok "Docker Compose v2 found"
elif command -v docker-compose &>/dev/null; then
  warn "docker-compose v1 found. Recommend upgrading to Docker Compose v2."
else
  die "Docker Compose not found. Install: https://docs.docker.com/compose/install/"
fi

# ─── Interactive prompts ──────────────────────────────────────────────────────

step "Configuration"

if [[ -z "$DOMAIN" ]]; then
  read -r -p "  Your domain (e.g. mail.example.com): " DOMAIN
fi
[[ -z "$DOMAIN" ]] && die "Domain is required."

if [[ -z "$ADMIN_EMAIL" ]]; then
  read -r -p "  Admin email address: " ADMIN_EMAIL
fi
[[ -z "$ADMIN_EMAIL" ]] && die "Admin email is required."

info "Install directory: ${INSTALL_DIR}"
read -r -p "  Press Enter to confirm, or type a different path: " CUSTOM_DIR
[[ -n "$CUSTOM_DIR" ]] && INSTALL_DIR="$CUSTOM_DIR"

# ─── Generate secrets ─────────────────────────────────────────────────────────

step "Generating secrets"

PLATFORM_ENCRYPTION_KEY=$(openssl rand -base64 32)
SUPABASE_JWT_SECRET=$(openssl rand -base64 64 | tr -d '\n')
UPINBOX_LICENSE_SIGNING_KEY=$(openssl rand -base64 32)
NEXTAUTH_SECRET=$(openssl rand -base64 32)

ok "PLATFORM_ENCRYPTION_KEY generated"
ok "SUPABASE_JWT_SECRET generated"
ok "UPINBOX_LICENSE_SIGNING_KEY generated"
ok "NEXTAUTH_SECRET generated"

# ─── Create install directory ─────────────────────────────────────────────────

step "Creating install directory"

mkdir -p "${INSTALL_DIR}"
cd "${INSTALL_DIR}"
ok "Created ${INSTALL_DIR}"

# ─── Write .env ───────────────────────────────────────────────────────────────

step "Writing .env"

cat > .env <<EOF
# UpInbox — Self-Hosted Configuration
# Generated by setup.sh on $(date -u +"%Y-%m-%dT%H:%M:%SZ")
# DO NOT COMMIT THIS FILE — add it to .gitignore

# ── Core ─────────────────────────────────────────────────────────────────────
NEXT_PUBLIC_APP_URL=https://${DOMAIN}
INSTANCE_DOMAIN=${DOMAIN}
ADMIN_EMAIL=${ADMIN_EMAIL}
NEXTAUTH_SECRET=${NEXTAUTH_SECRET}
NEXTAUTH_URL=https://${DOMAIN}

# ── Encryption ────────────────────────────────────────────────────────────────
# KEEP THIS SAFE. Losing it means losing access to all stored credentials.
# Never share it. Never commit it. Store it in your secret manager.
PLATFORM_ENCRYPTION_KEY=${PLATFORM_ENCRYPTION_KEY}

# ── License ───────────────────────────────────────────────────────────────────
# Used to verify self-hosted license JWTs
UPINBOX_LICENSE_SIGNING_KEY=${UPINBOX_LICENSE_SIGNING_KEY}
# Paste your license JWT here (get one at https://upinbox.ai/license)
UPINBOX_LICENSE_JWT=

# ── Database (Supabase) ──────────────────────────────────────────────────────
NEXT_PUBLIC_SUPABASE_URL=http://localhost:54321
NEXT_PUBLIC_SUPABASE_ANON_KEY=your-anon-key-from-supabase-start
SUPABASE_SERVICE_ROLE_KEY=your-service-role-key-from-supabase-start
SUPABASE_JWT_SECRET=${SUPABASE_JWT_SECRET}

# ── AI (BYOK — optional, user-supplied in browser) ───────────────────────────
# These are NOT used server-side. Users supply their own keys in the browser.
# Set these if you want server-side Intelligence API (business license required)
INTELLIGENCE_API_ENABLED=false

# ── Email (Stalwart — optional, for @yourdomain.com addresses) ───────────────
STALWART_ENABLED=false
STALWART_ADMIN_SECRET=$(openssl rand -hex 16)

# ── Stripe (optional — for hosted billing) ───────────────────────────────────
STRIPE_SECRET_KEY=
STRIPE_WEBHOOK_SECRET=
NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY=

# ── Google OAuth (optional — for Gmail integration) ───────────────────────────
GOOGLE_CLIENT_ID=
GOOGLE_CLIENT_SECRET=

# ── Microsoft OAuth (optional — for Outlook integration) ──────────────────────
MICROSOFT_CLIENT_ID=
MICROSOFT_CLIENT_SECRET=
MICROSOFT_TENANT_ID=common
EOF

ok ".env written"
warn "IMPORTANT: Back up your .env file securely. PLATFORM_ENCRYPTION_KEY cannot be recovered."

# ─── Download docker-compose.yml ─────────────────────────────────────────────

step "Downloading docker-compose.yml"

if [[ -f docker-compose.yml ]]; then
  ok "docker-compose.yml already exists — skipping download"
else
  if command -v curl &>/dev/null; then
    curl -fsSL "https://raw.githubusercontent.com/UpGPT-ai/upinbox/main/docker-compose.yml" \
      -o docker-compose.yml
  elif command -v wget &>/dev/null; then
    wget -q "https://raw.githubusercontent.com/UpGPT-ai/upinbox/main/docker-compose.yml" \
      -O docker-compose.yml
  else
    die "Neither curl nor wget found. Please download docker-compose.yml manually."
  fi
  ok "docker-compose.yml downloaded"
fi

# ─── Pull images ─────────────────────────────────────────────────────────────

step "Pulling Docker images (this takes a few minutes on first run)"

docker compose pull

# ─── Print next steps ─────────────────────────────────────────────────────────

echo
echo -e "${GREEN}${BOLD}✓ Setup complete!${NC}"
echo
echo "  Install directory: ${INSTALL_DIR}"
echo
echo -e "${BOLD}Next steps:${NC}"
echo
echo "  1. Configure Supabase:"
echo "     cd ${INSTALL_DIR}"
echo "     docker compose up supabase -d"
echo "     # Copy the anon key + service role key from the output into .env"
echo
echo "  2. Start UpInbox:"
echo "     docker compose up -d"
echo
echo "  3. Open https://${DOMAIN} and create your admin account"
echo
echo "  4. (Optional) Get a free Community license at https://upinbox.ai/license"
echo "     and paste the JWT into UPINBOX_LICENSE_JWT in .env"
echo
echo -e "${YELLOW}Docs: https://upinbox.ai/docs/SELF-HOSTING.md${NC}"
echo
